# Generated by Django 4.2.1 on 2023-05-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="measurement_photos/",
                verbose_name="Фотография помещения",
            ),
        ),
    ]
