# Generated by Django 4.2 on 2023-05-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0002_alter_phone_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
